/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpcomingRouteImport } from './routes/upcoming'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TaskNewRouteImport } from './routes/task.new'
import { Route as TaskIdRouteImport } from './routes/task.$id'
import { Route as OauthGoogleReturnRouteImport } from './routes/oauth/google/return'
import { Route as ApiPublicDailyReportRouteImport } from './routes/api/public/daily-report'
import { Route as ApiPublicGoogleCalendarIndexRouteImport } from './routes/api/public/google-calendar/index'
import { Route as ApiPublicGoogleCalendarSyncRouteImport } from './routes/api/public/google-calendar/sync'
import { Route as ApiPublicGoogleCalendarStatusRouteImport } from './routes/api/public/google-calendar/status'
import { Route as ApiPublicGoogleCalendarStartRouteImport } from './routes/api/public/google-calendar/start'
import { Route as ApiPublicGoogleCalendarDisconnectRouteImport } from './routes/api/public/google-calendar/disconnect'
import { Route as ApiPublicGoogleCalendarCompleteRouteImport } from './routes/api/public/google-calendar/complete'

const UpcomingRoute = UpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskNewRoute = TaskNewRouteImport.update({
  id: '/task/new',
  path: '/task/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskIdRoute = TaskIdRouteImport.update({
  id: '/task/$id',
  path: '/task/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthGoogleReturnRoute = OauthGoogleReturnRouteImport.update({
  id: '/oauth/google/return',
  path: '/oauth/google/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDailyReportRoute = ApiPublicDailyReportRouteImport.update({
  id: '/api/public/daily-report',
  path: '/api/public/daily-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGoogleCalendarIndexRoute =
  ApiPublicGoogleCalendarIndexRouteImport.update({
    id: '/api/public/google-calendar/',
    path: '/api/public/google-calendar/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGoogleCalendarSyncRoute =
  ApiPublicGoogleCalendarSyncRouteImport.update({
    id: '/api/public/google-calendar/sync',
    path: '/api/public/google-calendar/sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGoogleCalendarStatusRoute =
  ApiPublicGoogleCalendarStatusRouteImport.update({
    id: '/api/public/google-calendar/status',
    path: '/api/public/google-calendar/status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGoogleCalendarStartRoute =
  ApiPublicGoogleCalendarStartRouteImport.update({
    id: '/api/public/google-calendar/start',
    path: '/api/public/google-calendar/start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGoogleCalendarDisconnectRoute =
  ApiPublicGoogleCalendarDisconnectRouteImport.update({
    id: '/api/public/google-calendar/disconnect',
    path: '/api/public/google-calendar/disconnect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGoogleCalendarCompleteRoute =
  ApiPublicGoogleCalendarCompleteRouteImport.update({
    id: '/api/public/google-calendar/complete',
    path: '/api/public/google-calendar/complete',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/journal': typeof JournalRoute
  '/privacy': typeof PrivacyRoute
  '/upcoming': typeof UpcomingRoute
  '/task/$id': typeof TaskIdRoute
  '/task/new': typeof TaskNewRoute
  '/api/public/daily-report': typeof ApiPublicDailyReportRoute
  '/oauth/google/return': typeof OauthGoogleReturnRoute
  '/api/public/google-calendar/complete': typeof ApiPublicGoogleCalendarCompleteRoute
  '/api/public/google-calendar/disconnect': typeof ApiPublicGoogleCalendarDisconnectRoute
  '/api/public/google-calendar/start': typeof ApiPublicGoogleCalendarStartRoute
  '/api/public/google-calendar/status': typeof ApiPublicGoogleCalendarStatusRoute
  '/api/public/google-calendar/sync': typeof ApiPublicGoogleCalendarSyncRoute
  '/api/public/google-calendar/': typeof ApiPublicGoogleCalendarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/journal': typeof JournalRoute
  '/privacy': typeof PrivacyRoute
  '/upcoming': typeof UpcomingRoute
  '/task/$id': typeof TaskIdRoute
  '/task/new': typeof TaskNewRoute
  '/api/public/daily-report': typeof ApiPublicDailyReportRoute
  '/oauth/google/return': typeof OauthGoogleReturnRoute
  '/api/public/google-calendar/complete': typeof ApiPublicGoogleCalendarCompleteRoute
  '/api/public/google-calendar/disconnect': typeof ApiPublicGoogleCalendarDisconnectRoute
  '/api/public/google-calendar/start': typeof ApiPublicGoogleCalendarStartRoute
  '/api/public/google-calendar/status': typeof ApiPublicGoogleCalendarStatusRoute
  '/api/public/google-calendar/sync': typeof ApiPublicGoogleCalendarSyncRoute
  '/api/public/google-calendar': typeof ApiPublicGoogleCalendarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/journal': typeof JournalRoute
  '/privacy': typeof PrivacyRoute
  '/upcoming': typeof UpcomingRoute
  '/task/$id': typeof TaskIdRoute
  '/task/new': typeof TaskNewRoute
  '/api/public/daily-report': typeof ApiPublicDailyReportRoute
  '/oauth/google/return': typeof OauthGoogleReturnRoute
  '/api/public/google-calendar/complete': typeof ApiPublicGoogleCalendarCompleteRoute
  '/api/public/google-calendar/disconnect': typeof ApiPublicGoogleCalendarDisconnectRoute
  '/api/public/google-calendar/start': typeof ApiPublicGoogleCalendarStartRoute
  '/api/public/google-calendar/status': typeof ApiPublicGoogleCalendarStatusRoute
  '/api/public/google-calendar/sync': typeof ApiPublicGoogleCalendarSyncRoute
  '/api/public/google-calendar/': typeof ApiPublicGoogleCalendarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/journal'
    | '/privacy'
    | '/upcoming'
    | '/task/$id'
    | '/task/new'
    | '/api/public/daily-report'
    | '/oauth/google/return'
    | '/api/public/google-calendar/complete'
    | '/api/public/google-calendar/disconnect'
    | '/api/public/google-calendar/start'
    | '/api/public/google-calendar/status'
    | '/api/public/google-calendar/sync'
    | '/api/public/google-calendar/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/journal'
    | '/privacy'
    | '/upcoming'
    | '/task/$id'
    | '/task/new'
    | '/api/public/daily-report'
    | '/oauth/google/return'
    | '/api/public/google-calendar/complete'
    | '/api/public/google-calendar/disconnect'
    | '/api/public/google-calendar/start'
    | '/api/public/google-calendar/status'
    | '/api/public/google-calendar/sync'
    | '/api/public/google-calendar'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/journal'
    | '/privacy'
    | '/upcoming'
    | '/task/$id'
    | '/task/new'
    | '/api/public/daily-report'
    | '/oauth/google/return'
    | '/api/public/google-calendar/complete'
    | '/api/public/google-calendar/disconnect'
    | '/api/public/google-calendar/start'
    | '/api/public/google-calendar/status'
    | '/api/public/google-calendar/sync'
    | '/api/public/google-calendar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  JournalRoute: typeof JournalRoute
  PrivacyRoute: typeof PrivacyRoute
  UpcomingRoute: typeof UpcomingRoute
  TaskIdRoute: typeof TaskIdRoute
  TaskNewRoute: typeof TaskNewRoute
  ApiPublicDailyReportRoute: typeof ApiPublicDailyReportRoute
  OauthGoogleReturnRoute: typeof OauthGoogleReturnRoute
  ApiPublicGoogleCalendarCompleteRoute: typeof ApiPublicGoogleCalendarCompleteRoute
  ApiPublicGoogleCalendarDisconnectRoute: typeof ApiPublicGoogleCalendarDisconnectRoute
  ApiPublicGoogleCalendarStartRoute: typeof ApiPublicGoogleCalendarStartRoute
  ApiPublicGoogleCalendarStatusRoute: typeof ApiPublicGoogleCalendarStatusRoute
  ApiPublicGoogleCalendarSyncRoute: typeof ApiPublicGoogleCalendarSyncRoute
  ApiPublicGoogleCalendarIndexRoute: typeof ApiPublicGoogleCalendarIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upcoming': {
      id: '/upcoming'
      path: '/upcoming'
      fullPath: '/upcoming'
      preLoaderRoute: typeof UpcomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task/new': {
      id: '/task/new'
      path: '/task/new'
      fullPath: '/task/new'
      preLoaderRoute: typeof TaskNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task/$id': {
      id: '/task/$id'
      path: '/task/$id'
      fullPath: '/task/$id'
      preLoaderRoute: typeof TaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/google/return': {
      id: '/oauth/google/return'
      path: '/oauth/google/return'
      fullPath: '/oauth/google/return'
      preLoaderRoute: typeof OauthGoogleReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/daily-report': {
      id: '/api/public/daily-report'
      path: '/api/public/daily-report'
      fullPath: '/api/public/daily-report'
      preLoaderRoute: typeof ApiPublicDailyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google-calendar/': {
      id: '/api/public/google-calendar/'
      path: '/api/public/google-calendar'
      fullPath: '/api/public/google-calendar/'
      preLoaderRoute: typeof ApiPublicGoogleCalendarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google-calendar/sync': {
      id: '/api/public/google-calendar/sync'
      path: '/api/public/google-calendar/sync'
      fullPath: '/api/public/google-calendar/sync'
      preLoaderRoute: typeof ApiPublicGoogleCalendarSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google-calendar/status': {
      id: '/api/public/google-calendar/status'
      path: '/api/public/google-calendar/status'
      fullPath: '/api/public/google-calendar/status'
      preLoaderRoute: typeof ApiPublicGoogleCalendarStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google-calendar/start': {
      id: '/api/public/google-calendar/start'
      path: '/api/public/google-calendar/start'
      fullPath: '/api/public/google-calendar/start'
      preLoaderRoute: typeof ApiPublicGoogleCalendarStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google-calendar/disconnect': {
      id: '/api/public/google-calendar/disconnect'
      path: '/api/public/google-calendar/disconnect'
      fullPath: '/api/public/google-calendar/disconnect'
      preLoaderRoute: typeof ApiPublicGoogleCalendarDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google-calendar/complete': {
      id: '/api/public/google-calendar/complete'
      path: '/api/public/google-calendar/complete'
      fullPath: '/api/public/google-calendar/complete'
      preLoaderRoute: typeof ApiPublicGoogleCalendarCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  JournalRoute: JournalRoute,
  PrivacyRoute: PrivacyRoute,
  UpcomingRoute: UpcomingRoute,
  TaskIdRoute: TaskIdRoute,
  TaskNewRoute: TaskNewRoute,
  ApiPublicDailyReportRoute: ApiPublicDailyReportRoute,
  OauthGoogleReturnRoute: OauthGoogleReturnRoute,
  ApiPublicGoogleCalendarCompleteRoute: ApiPublicGoogleCalendarCompleteRoute,
  ApiPublicGoogleCalendarDisconnectRoute:
    ApiPublicGoogleCalendarDisconnectRoute,
  ApiPublicGoogleCalendarStartRoute: ApiPublicGoogleCalendarStartRoute,
  ApiPublicGoogleCalendarStatusRoute: ApiPublicGoogleCalendarStatusRoute,
  ApiPublicGoogleCalendarSyncRoute: ApiPublicGoogleCalendarSyncRoute,
  ApiPublicGoogleCalendarIndexRoute: ApiPublicGoogleCalendarIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
