/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpcomingRouteImport } from './routes/upcoming'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TaskNewRouteImport } from './routes/task.new'
import { Route as TaskIdRouteImport } from './routes/task.$id'
import { Route as ApiPublicDailyReportRouteImport } from './routes/api/public/daily-report'

const UpcomingRoute = UpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskNewRoute = TaskNewRouteImport.update({
  id: '/task/new',
  path: '/task/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskIdRoute = TaskIdRouteImport.update({
  id: '/task/$id',
  path: '/task/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDailyReportRoute = ApiPublicDailyReportRouteImport.update({
  id: '/api/public/daily-report',
  path: '/api/public/daily-report',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/journal': typeof JournalRoute
  '/upcoming': typeof UpcomingRoute
  '/task/$id': typeof TaskIdRoute
  '/task/new': typeof TaskNewRoute
  '/api/public/daily-report': typeof ApiPublicDailyReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/journal': typeof JournalRoute
  '/upcoming': typeof UpcomingRoute
  '/task/$id': typeof TaskIdRoute
  '/task/new': typeof TaskNewRoute
  '/api/public/daily-report': typeof ApiPublicDailyReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/journal': typeof JournalRoute
  '/upcoming': typeof UpcomingRoute
  '/task/$id': typeof TaskIdRoute
  '/task/new': typeof TaskNewRoute
  '/api/public/daily-report': typeof ApiPublicDailyReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/journal'
    | '/upcoming'
    | '/task/$id'
    | '/task/new'
    | '/api/public/daily-report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/journal'
    | '/upcoming'
    | '/task/$id'
    | '/task/new'
    | '/api/public/daily-report'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/journal'
    | '/upcoming'
    | '/task/$id'
    | '/task/new'
    | '/api/public/daily-report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  JournalRoute: typeof JournalRoute
  UpcomingRoute: typeof UpcomingRoute
  TaskIdRoute: typeof TaskIdRoute
  TaskNewRoute: typeof TaskNewRoute
  ApiPublicDailyReportRoute: typeof ApiPublicDailyReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upcoming': {
      id: '/upcoming'
      path: '/upcoming'
      fullPath: '/upcoming'
      preLoaderRoute: typeof UpcomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task/new': {
      id: '/task/new'
      path: '/task/new'
      fullPath: '/task/new'
      preLoaderRoute: typeof TaskNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task/$id': {
      id: '/task/$id'
      path: '/task/$id'
      fullPath: '/task/$id'
      preLoaderRoute: typeof TaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/daily-report': {
      id: '/api/public/daily-report'
      path: '/api/public/daily-report'
      fullPath: '/api/public/daily-report'
      preLoaderRoute: typeof ApiPublicDailyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  JournalRoute: JournalRoute,
  UpcomingRoute: UpcomingRoute,
  TaskIdRoute: TaskIdRoute,
  TaskNewRoute: TaskNewRoute,
  ApiPublicDailyReportRoute: ApiPublicDailyReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
